### ISSUE TITLE
Maximising a RibbonWindow with MaxWidth or MaxHeight causes an extra border above the title bar

### ISSUE THREAD

**Issue by batzen** [ControlzEx/ControlzEx#31]
Copied from https://github.com/fluentribbon/Fluent.Ribbon/issues/456 
> If a RibbonWindow has either MaxWidth or MaxHeight set (to a value less than the screen size), when maximising the window there is an extra border along the top edge. Looking closely it appears that there's extra window chrome being shown around the edge of the ribbon window, but it's more obvious at the top edge because there are tiny minimise/maximise/close buttons in the corner separate from the ribbon's buttons.

> It's colour is independent from the ribbon background so stands out on a dark theme.

> I can reproduce it in the showcase application by adding MaxWidth="1000" to TestWindow.xaml.

> Screenshot (the red border I added in paint to highlight where it is :))
![border](https://user-images.githubusercontent.com/26153437/29319398-d557e958-81cb-11e7-81c9-b6e1ecba4b82.png)

**Comment by batzen** [comment]
My fix did not work as expected. As mentioned in https://github.com/fluentribbon/Fluent.Ribbon/issues/456

**Comment by batzen** [comment]
Should be fixed now.
@Cubey2019 could you have a look?

**Comment by Cubey2019** [comment]
I won't have access to the same environment until Tuesday, but I've had a quick run through on a different PC and couldn't reproduce any of the problems in the ControlzEx Showcase. If I build the Fluent Ribbon Showcase against these changes I'm still seeing issues there (e.g. SizeToContent="WidthAndHeight" overflows to the second monitor).

Something else I have noticed is that if you add SizeToContent="WidthAndHeight" to MainWindow.xaml and maximise the window its size doesn't change (but it does dock to the top left of the screen). If you restore the window and maximise a second time then it will correctly fill the screen.

Thanks for taking the time to look into this.

**Comment by batzen** [comment]
@Cubey2019 Isn't that the expected behavior?
It keeps it's size as long as you don't resize the window.

**Comment by Cubey2019** [comment]
I think the behaviour a user would expect is for the window to grow or shrink to fill the current screen within the Min/Max size constraints (at least this is how I've always expected it to work :)). I noticed that it behaves as expected when using the right-click system menu to maximise, the difference is that SizeToContent is being reset to Manual in this case but not others. I checked the behaviour of a plain WPF Window and found that double clicking the titlebar or clicking the maximise button will reset the SizeToContent, so the problem is that the ControlzEx and Fluent windows aren't doing this. The plain WPF Window doesn't maximise properly (IMO) when dragging it to the top of the screen, so I guess that one's an issue with .NET/Windows.

As a quick test I've committed changes to a separate branch (https://github.com/Cubey2019/Fluent.Ribbon/commit/43db54bb06261a67f3ff26035f9086d634ebe9cf) so that the Fluent window will reset SizeToContent when maximising, and it seems to solve the problem here.



I've also gone through all of the scenarios again in both ControlzEx and Fluent (this time on the original environment). Ignoring the maximise-size issue above, ControlzEx looks good to me, I can't reproduce any of the border/rendering issues on the latest commit.

In Fluent there's still a remaining issue where adding `SizeToContent="WidthAndHeight" MaxHeight="800"` to TestWindow.xaml shows a black section when maximised (SizeToContent on its own is fine):

![sizetocontent maxheight](https://user-images.githubusercontent.com/26153437/29818935-56b1664c-8cb6-11e7-8d1e-aeb9fa717033.png)

**Comment by batzen** [comment]
Fixed the issue in Fluent.Ribbon with https://github.com/fluentribbon/Fluent.Ribbon/commit/bb498afedcd03975ebd0980636331db2c8f80104

**Comment by Cubey2019** [comment]
That commit fixes the window size when double clicking the title bar, but the maximise button still isn't right. I think the button Click handlers in WindowCommands should also be changed to call SystemCommands.MaximizeWindow/RestoreWindow/etc?

**Comment by batzen** [comment]
Yeah. Will change them later.

**Comment by batzen** [comment]
Fixed. Now SystemCommands are used everywhere to send window commands.

**Comment by Cubey2019** [comment]
Looks good. :)
The only problem left that I can see is the black section when maximising (I couldn't find a way to reproduce this in ControlzEx though, so could be a separate issue in Fluent.Ribbon).

I have also found a problem with the solution for fluentribbon/Fluent.Ribbon#454 but I'll explain there.

**Comment by batzen** [comment]
Nice. Will close this one then.
